  CREATE TABLE "SHARE_INFO" 
   (	"SHARE_URL" VARCHAR2(4000 CHAR), 
	"AWEME_ID" VARCHAR2(4000 CHAR), 
	 CONSTRAINT "SHARE_INFO_CON" PRIMARY KEY ("SHARE_URL")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "SHARE_INFO" ADD CONSTRAINT "SHARE_INFO_FK" FOREIGN KEY ("AWEME_ID")
	  REFERENCES "AWEME" ("AWEME_ID") ENABLE;