  CREATE TABLE "AWEME" 
   (	"AWEME_ID" VARCHAR2(4000 CHAR), 
	"CREATE_TIME" NUMBER, 
	"DESC_VIDEO" VARCHAR2(4000 CHAR), 
	"DESC_LANGUAGE" VARCHAR2(4000 CHAR), 
	 CONSTRAINT "AWEME_PK" PRIMARY KEY ("AWEME_ID")
  USING INDEX  ENABLE
   ) ;